// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jotai from "jotai";

var InventoryItem = {};

var ExecutorConfig = {};

var executorConfigAtom = Jotai.atom(async function () {
      var response = await fetch("https://62210a40afd560ea69a5c07b.mockapi.io/mock", {
            method: "GET"
          });
      return [
              JSON.parse(await response.text()),
              undefined
            ];
    });

function useExecutor() {
  return Jotai.useAtomValue(executorConfigAtom)[0];
}

export {
  InventoryItem ,
  ExecutorConfig ,
  useExecutor ,
}
/* executorConfigAtom Not a pure module */
