// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

var InventoryItem = {};

var ExecutorConfig = {};

function useExecutor(url) {
  var match = React.useState(function () {
        return "LoadingEndpoint";
      });
  var setState = match[1];
  React.useEffect((function () {
          var request = new XMLHttpRequest();
          request.addEventListener("load", (function () {
                  setState(function (_previousState) {
                        return {
                                TAG: "LoadedEndpoint",
                                _0: JSON.parse(request.response)
                              };
                      });
                }));
          request.addEventListener("error", (function () {
                  setState(function (_previousState) {
                        return "ErrorLoadingEndpoint";
                      });
                }));
          request.open("GET", url);
          request.send();
          return (function () {
                    request.abort();
                  });
        }), []);
  return match[0];
}

export {
  InventoryItem ,
  ExecutorConfig ,
  useExecutor ,
}
/* react Not a pure module */
