// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Landing from "../Landing/Landing.res.mjs";
import * as ErrorView from "../ErrorView/ErrorView.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.res.mjs";

function App(props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  if (!match) {
    return JsxRuntime.jsx(Landing.make, {});
  }
  if (match.hd !== "item") {
    return JsxRuntime.jsx(ErrorView.make, {});
  }
  var match$1 = match.tl;
  if (match$1) {
    return JsxRuntime.jsx(Landing.make, {
                activeIdOpt: match$1.hd
              });
  } else {
    return JsxRuntime.jsx(ErrorView.make, {});
  }
}

var make = App;

export {
  make ,
}
/* Landing Not a pure module */
