// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Landing from "../Landing/Landing.mjs";
import * as Belt_Int from "rescript/lib/es6/belt_Int.js";
import * as ErrorView from "../ErrorView/ErrorView.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.mjs";

function App(props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  if (!match) {
    return JsxRuntime.jsx(Landing.make, {});
  }
  if (match.hd !== "item") {
    return JsxRuntime.jsx(ErrorView.make, {});
  }
  var match$1 = match.tl;
  if (!match$1) {
    return JsxRuntime.jsx(ErrorView.make, {});
  }
  if (match$1.tl) {
    return JsxRuntime.jsx(ErrorView.make, {});
  }
  var id = Belt_Int.fromString(match$1.hd);
  var id$1 = id !== undefined ? id : -1;
  return JsxRuntime.jsx(Landing.make, {
              activeId: id$1
            });
}

var make = App;

export {
  make ,
}
/* Landing Not a pure module */
