// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cart from "../Cart/Cart.res.mjs";
import * as React from "react";
import * as Js_array from "rescript/lib/es6/js_array.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.res.mjs";

function str(prim) {
  return prim;
}

function InventoryItem(props) {
  var __active = props.active;
  var item = props.item;
  var active = __active !== undefined ? __active : false;
  var id = item.id;
  React.useContext(Cart.DispatchContext.context);
  var cartState = React.useContext(Cart.StateContext.context);
  var matches = Js_array.filter((function (cart_item) {
          return cart_item === item.id;
        }), cartState.cart);
  var matchCount = matches.length;
  var quantity = matchCount > 0 ? String(matches.length) : "0";
  var available = String(item.quantity - matchCount | 0);
  return JsxRuntime.jsx("a", {
              children: JsxRuntime.jsxs("button", {
                    children: [
                      JsxRuntime.jsx("div", {
                            children: JsxRuntime.jsx("img", {
                                  className: "p-[1.5]",
                                  style: {
                                    width: "100%"
                                  },
                                  src: "https://placeholdr.ai/1ca27004-f6f9-413a-8dbf-6c088feabead/256/256?" + String(id)
                                }),
                            className: "rounded border-2 shadow m-0 p-0"
                          }),
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsxs("span", {
                                    children: [
                                      JsxRuntime.jsx("i", {
                                            className: "light-icon-shopping-cart text-xl"
                                          }),
                                      JsxRuntime.jsx("span", {
                                            children: quantity,
                                            className: "text-[0.5rem]",
                                            title: "Quantity in cart"
                                          })
                                    ],
                                    className: "drop-shadow"
                                  }),
                              JsxRuntime.jsxs("span", {
                                    children: [
                                      JsxRuntime.jsx("i", {
                                            className: "light-icon-checks text-xl"
                                          }),
                                      JsxRuntime.jsx("span", {
                                            children: available,
                                            className: "text-[0.5rem]",
                                            title: "Quantity available"
                                          })
                                    ],
                                    className: "drop-shadow"
                                  })
                            ],
                            className: "flex flex-row justify-between w-full bg-gray-300 text-white shadow"
                          }),
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("h2", {
                                    children: item.title,
                                    className: "w-full text-xs drop-shadow text-gray-500"
                                  }),
                              JsxRuntime.jsx("p", {
                                    children: item.description,
                                    className: (
                                      active === false ? "hidden " : ""
                                    ) + "text-xs m-2"
                                  })
                            ],
                            className: "flex flex-col text-align-center w-full bg-white text-gray-300 rounded m-[1.5] justify-self-end"
                          })
                    ],
                    className: "relative m-[1.5] flex flex-col block"
                  }),
              className: "active:col-span-4 target:col-span-4 lg:active:col-span-8 lg:target:col-span-8 block",
              id: "item-" + String(id),
              href: "/item/" + String(id),
              onClick: (function (_e) {
                  RescriptReactRouter.push("item/" + String(id));
                })
            });
}

var make = InventoryItem;

export {
  str ,
  make ,
}
/* Cart Not a pure module */
